#!/bin/sh

echo '创建资料项目的文档管理目录树'

mkdir -p 文保和世界遗产
mkdir -p 文保和世界遗产/文保碑
mkdir -p 文保和世界遗产/世界遗产
mkdir -p 文保和世界遗产/国保碑

mkdir -p 西山研究

mkdir -p 家庭
mkdir -p 家庭/票据
mkdir -p 家庭/课外班发票
mkdir -p 家庭/房子

mkdir -p 家庭/车
mkdir -p 家庭/车/违章记录
mkdir -p 家庭/车/停车证

mkdir -p 公司
mkdir -p 宜家
mkdir -p 长城
mkdir -p 老照片
mkdir -p 老照片/扫描
mkdir -p 老照片/黑白
mkdir -p 老照片/合影
mkdir -p 老照片/底板扫描
mkdir -p 老照片/爸妈
mkdir -p 老照片/PS
